version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/	
  - source: /webpages/page1.html
    destination: /var/www/html/	
  - source: /codedeploydemopro
    destination: /opt/apache-tomcat-8.0.41/webapps/codedeploydemopro
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

